SELECT (34+346-67)/15*29 as resultado;

SELECT ceiling(3.1416);

SELECT floor(3.1416);

SELECT rand() as resultado;

select round(254.545,2);

SELECT NUMERO, CANTIDAD, PRECIO, 
round(CANTIDAD*PRECIO,2) AS FACTURACION 
FROM items_facturas;

SELECT YEAR(FECHA_VENTA), FLOOR(SUM(IMPUESTO * (CANTIDAD * PRECIO))) 
AS RESULTADO
FROM facturas F
INNER JOIN items_facturas IFa ON F.NUMERO = IFa.NUMERO
WHERE YEAR(FECHA_VENTA) = 2016
GROUP BY YEAR(FECHA_VENTA);

