SELECT * FROM facturas;

SELECT * FROM items_facturas;

SELECT F.DNI, F.FECHA_VENTA, IFa.CANTIDAD FROM facturas F
INNER JOIN
items_facturas IFa
ON F.NUMERO = IFa.NUMERO;

SELECT F.DNI, date_format(F.FECHA_VENTA, '%M-%Y') AS FECHA,
IFa.CANTIDAD FROM facturas F
INNER JOIN
items_facturas IFa
ON F.NUMERO = IFa.NUMERO;

/* CANTIDAD DE VENTAS POR MES POR CLIENTE */
SELECT F.DNI, date_format(F.FECHA_VENTA, '%M-%Y') AS FECHA,
sum(IFa.CANTIDAD) AS cantidad_vendida
FROM facturas F
INNER JOIN
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
GROUP BY F.DNI, date_format(F.FECHA_VENTA, '%M-%Y');

/* ventas inválidas y calcula la diferencia 
entre el límite de venta máximo y la cantidad 
vendida en porcentuales */
SELECT A.DNI, A.NOMBRE, A.MES_AÑO, A.CANTIDAD_VENDIDA, A.CANTIDAD_MAXIMA,
A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
CASE
   WHEN  (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEN 'Venta Válida'
   ELSE 'Venta Inválida'
END AS STATUS_VENTA, ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) AS PORCENTAJE
 FROM(
SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA  
FROM facturas F 
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN 
tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY
F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y"))A
WHERE (A.CANTIDAD_MAXIMA - A.CANTIDAD_VENDIDA) < 0;

/* LIMITE DE VENTAS POR CLIENTE */
SELECT * FROM tabla_de_clientes TC;
SELECT DNI, NOMBRE, VOLUMEN_DE_COMPRA
FROM tabla_de_clientes TC;

SELECT F.DNI, TC.NOMBRE, 
date_format(F.FECHA_VENTA, '%M-%Y') AS MES_AÑO,
sum(IFa.CANTIDAD) AS cantidad_vendida,
MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA
FROM facturas F
INNER JOIN items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN tabla_de_clientes TC
ON F.DNI = TC.DNI
GROUP BY F.DNI, TC.NOMBRE, date_format(F.FECHA_VENTA, '%M-%Y');

SELECT A.DNI, A.NOMBRE, A.MES_AÑO, A.CANTIDAD_VENDIDA, A.CANTIDAD_MAXIMA,
A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
CASE
   WHEN  (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEN 'Venta Válida'
   ELSE 'Venta Inválida'
END AS STATUS_VENTA, ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) AS PORCENTAJE
 FROM(
	SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, 
	SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
	MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA  
	FROM facturas F 
	INNER JOIN 
	items_facturas IFa
	ON F.NUMERO = IFa.NUMERO
	INNER JOIN 
	tabla_de_clientes TC
	ON TC.DNI = F.DNI
	GROUP BY
F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y"))A
WHERE (A.CANTIDAD_MAXIMA - A.CANTIDAD_VENDIDA) < 0;

SELECT A.DNI, A.NOMBRE, A.MES_AÑO, 
A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
CASE
   WHEN  (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEN 'Venta Válida'
   ELSE 'Venta Inválida'
END AS STATUS_VENTA, ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) AS PORCENTAJE
 FROM(
SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA  
FROM facturas F 
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN 
tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY
F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y"))A
WHERE (A.CANTIDAD_MAXIMA - A.CANTIDAD_VENDIDA) < 0 AND ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) > 50
AND A.MES_AÑO LIKE "%2018";