SELECT * FROM tabla_de_vendedores v
INNER JOIN facturas f
ON v.MATRICULA = f.MATRICULA;

SELECT v.NOMBRE, f.MATRICULA, COUNT(*) 
FROM tabla_de_vendedores v
INNER JOIN facturas f
ON v.MATRICULA = f.MATRICULA
GROUP BY v.NOMBRE, f.MATRICULA;

SELECT YEAR(FECHA_VENTA), SUM(CANTIDAD * PRECIO) AS FACTURACION
FROM facturas F 
INNER JOIN 
items_facturas IFa 
ON F.NUMERO = IFa.NUMERO
GROUP BY YEAR(FECHA_VENTA);