SELECT ENVASE, MAX(precio_de_lista)
AS PRECIO_MAXIMO FROM tabla_de_productos GROUP BY ENVASE;

SELECT X.ENVASE, X.PRECIO_MAXIMO FROM
vw_envases_grandes X
WHERE PRECIO_MAXIMO >= 10;

SELECT a.NOMBRE_DEL_PRODUCTO, a.ENVASE, a.PRECIO_DE_LISTA,
b.PRECIO_MAXIMO FROM tabla_de_productos a
INNER JOIN vw_envases_grandes b
ON a.ENVASE = b.ENVASE;

SELECT a.NOMBRE_DEL_PRODUCTO, a.ENVASE, 
a.PRECIO_DE_LISTA, b.PRECIO_MAXIMO,
((a.PRECIO_DE_LISTA/b.PRECIO_MAXIMO)-1)*100 AS PORCENTAJE_VARIACION
FROM tabla_de_productos a
INNER JOIN vw_envases_grandes b
ON a.ENVASE = b.ENVASE;