CREATE TABLE clientes (
DNI VARCHAR(11) NOT NULL,
NOMBRE VARCHAR(100) NULL,
DIRECCION VARCHAR (150),
BARRIO VARCHAR(50),
CIUDAD VARCHAR(50),
ESTADO VARCHAR(10),
CP VARCHAR(10),
FECHA_NACIMIENTO DATE,
EDAD SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUMEN_COMPRA FLOAT,
PRIMERA_COMPRA BIT,
PRIMARY KEY(DNI)
);

CREATE TABLE `empresa`.`vendedor` (
  `MATRICULA` VARCHAR(5) NOT NULL,
  `NOMBRE` VARCHAR(100) NULL,
  `BARRIO` VARCHAR(50) NULL,
  `COMISION` FLOAT NULL,
  `FECHA_ADMISION` DATE NULL,
  `VACACIONES` BIT(1) NULL,
  PRIMARY KEY (`MATRICULA`));
  
ALTER TABLE vendedor RENAME TO vendedores;

CREATE TABLE productos(
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(100),
SABOR VARCHAR(50),
TAMANO VARCHAR(50),
ENVASE VARCHAR(50),
PRECIO FLOAT,
PRIMARY KEY(CODIGO)
);

CREATE TABLE facturas(
NUMERO VARCHAR(5) NOT NULL,
FECHA DATE,
DNI VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPUESTO FLOAT,
PRIMARY KEY(NUMERO),
FOREIGN KEY(DNI) REFERENCES clientes(DNI),
FOREIGN KEY(MATRICULA) REFERENCES vendedores(MATRICULA)
);

DROP TABLE items;

CREATE TABLE items(
NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
CANTIDAD INT,
PRECIO FLOAT,
PRIMARY KEY(NUMERO, CODIGO),
FOREIGN KEY(NUMERO) REFERENCES facturas(NUMERO),
FOREIGN KEY(CODIGO) REFERENCES productos(CODIGO)
);

SELECT * FROM clientes;
SELECT * FROM productos;
SELECT * FROM vendedores;

SET GLOBAL log_bin_trust_function_creators = 1;

SELECT 
	f_cliente_aleatorio() AS CLIENTE, 
    f_producto_aleatorio() AS PRODUCTO, 
    f_vendedor_aleatorio() AS VENDEDOR;








